

# docker push registry.gitlab.com/kencove/odoo/outside-projects/docker-odoo-project

build:
  stage: build
  tags:
    - staging,cache
  image: docker:19.03.12

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    # DOCKER_HOST: tcp://docker:2376
    # DOCKER_TLS_VERIFY: 1
    # DOCKER_TLS_CERTDIR: "/certs"
    # DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

  services:
    - docker:19.03.12-dind

  before_script:
    - docker info
    - apk add --update make gcc bash
    - which gcc
  script:
    # generate image registry.gitlab.com/kencove/odoo/outside-projects/docker-odoo-project:14.0-latest and camptocamp/odoo-project:14.0-latest-onbuild
    - |
      if [[ -n "$CI_REGISTRY" && -n "$CI_REGISTRY_USER" ]]; then
        echo "Logging in to GitLab Container Registry with CI credentials..."
        echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
      fi

    - make VERSION=14.0
    - make VERSION=14.0 BATTERIES=True

  rules:
    - if: "$BUILD_DISABLED"
      when: never
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH"
